version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: usuario_pg
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: pure_life_db
    volumes:
      - ./datos_postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql